### PR TITLE
Generate output without namespace

### LINKED ISSUE #25: add feature to generate output without namespace
Currently, namespace parameter is required.

If one runs schemats without argument -n (or with empty one) like that : 
`schemats generate -c postgres://postgres@localhost/osm -t users -o osm.ts`

It ends up with the following output in osm.ts : 
```ts
export namespace undefined {

    export namespace usersFields {
...
```

Using a namespace for a whole module in typescript is ok, but a bit outdated.
With es2015 modules, it seems preferable to generate directly : 
```ts
    export namespace usersFields {
...
```

wich allows to import as following : 
```ts
import * as myNamespaceInConsumerModule from 'osm.ts'
...
```

It would be nice to make namespace optional.

### PR DESCRIPTION
**Pull request by abenhamdine**
Fixes #25

If namespace parameter is falsy (not provided or empty), don't generate anymore the namespace in the output file.

Sorry for the churn in artifact/osm.ts, I realized my indentation settings were different after having committed,

### CODE REVIEW

**Comment by abenhamdine** [comment]
CI has failed, however on my Windows 10 machine, the test has failed too, but I see no difference between example/osm.ts and output artifacts/osm.ts (I compared the two files in VS Code, Compare contextual menu).

So I'm unable to see what to change to make the test pass.

**Comment by xiamx** [comment]
Thanks for the patch!

Take a look at https://github.com/abenhamdine/schemats/pull/2 , I fixed the CI issue

**Comment by abenhamdine** [comment]
Ah thx a lot, CI is green now.

**Comment by xiamx** [comment]
Nice! I'll merge this together with fix for #31 and release v1.0

**Comment by abenhamdine** [comment]
IMHO a fix for #19 would be great for v1.0 (typescript users are sticklers for null checking these days 😉 )

**Comment by xiamx** [comment]
> IMHO a fix for #19 would be great for v1.0 (typescript users are sticklers for null checking these days 😉 )

Alright let's add that to the roadmap for v1.0 too . Let me know if you are pulling together a patch for any of those so we don't double the effort :)

**Comment by abenhamdine** [comment]
Ok, I will give a try for #19 and #31 on Sunday.

**Comment by xiamx** [comment]
Merged in here https://github.com/SweetIQ/schemats/commit/64143dd352ff1824417c288b248b016a003b4697

Thanks @abenhamdine

**Pull request closed without merging**
