### PR TITLE
Update schema.ts

### PR DESCRIPTION
**Pull request by vitaly-t**
simplifying the code.

### CODE REVIEW

**Comment by xiamx** [comment]
Thanks @vitaly-t ! Looks like some trailing space got caught by CI, could you make an update?

**Comment by vitaly-t** [comment]
ok, I removed the extra empty lines it complained about, but what doesn't it like now? :)

**Comment by xiamx** [comment]
It still complains about 
```
> schemats@0.1.8 lint /home/ubuntu/schemats
> tslint src/**/*.ts

src/schema.ts[12, 50]: trailing whitespace
src/schema.ts[20, 15]: trailing whitespace
```

You can run `npm run lint` locally to see these outputs

**Comment by vitaly-t** [comment]
fixing trailing spaces - this isn't developer-friendly, in case you want more contributions ;)

**Comment by xiamx** [comment]
True, disabling trailing space check on tslint.

Thanks for the help!

**Pull request merged**
